version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go mod download
      - run: go test -v ./...
      - run: go build

workflows:
  version: 2
  test:
    jobs:
      - test
